language: go
go_import_path: github.com/PlatONnetwork/PlatON-Go
# sudo: false
matrix:
  include:
    - name: code scan
      os: linux
      dist: xenial
      sudo: required
      go: 
        - 1.8.x
        - tip
      script:
        - sh ./build/build_deps.sh
        # - go test -race -coverprofile=coverage.txt -covermode=atomic
        # - go test -race -coverprofile=coverage.txt -covermode=atomic `go list ./... | grep -v swarm|grep -v tests|grep -v bn256`
        - go test -coverprofile=coverage.txt -covermode=atomic ./accounts
        
      after_success:
        - bash <(curl -s https://codecov.io/bash)