language: go
go_import_path: github.com/PlatONnetwork/PlatON-Go
# sudo: false
matrix:
  include:
    # This builders compile PlatON at Ubuntu xenial
    - name: ubuntu compile(make all)
      os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      script:
        - bash ./build/ci.sh ./ ubuntu false

    - name: ubuntu compile(make all with mv)
      os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      script:
        - bash ./build/ci.sh ./ ubuntu true

    # This builders compile PlatON at Windows server 2016
    - name: windows compile(make all)
      os: windows
      go: 1.12.x
      script:
        - bash ./build/ci.sh ./ windows false

    - name: windows compile(make all with mv)
      os: windows
      go: 1.12.x
      script:
        - bash ./build/ci.sh ./ windows true

    # # This builder run the code scans uses gometalinter
    # - name: code scan
    #   os: linux
    #   dist: xenial
    #   sudo: required
    #   go: 1.12.x
    #   script:
    #     - go get -v -u github.com/alecthomas/gometalinter
    #     - gometalinter --install --update
    #     - gometalinter --vendor --tests --deadline=10m --disable-all --enable=varcheck --enable=vet --enable=misspell --enable=goconst --min-occurrences=6 ./...

    # # This builder run the unit tests
    # - name: unit test
    #   os: linux
    #   dist: xenial
    #   sudo: required
    #   go: 1.12.x
    #   script:
    #     - sh ./build/build_deps.sh
    #     - go test `go list ./... | grep -v swarm|grep -v tests|grep -v bn256`

    # # This builder run the auto tests
    # - name: auto test
    #   os: linux
    #   dist: xenial
    #   sudo: required
    #   go: 1.12.x
    #   before_install:
    #     - pyenv install -f 3.6.0
    #     - pyenv rehash
    #     - pyenv global 3.6.0
    #     - python --version
    #     - pip --version
    #   install:
    #     - chmod u+x ./build/*.sh
    #     - make all
    #   script:
    #     - WORKSPACE=$(pwd)
    #     - git clone https://github.com/shinnng/PlatON-Tests.git
    #     - cd ${WORKSPACE}/PlatON-Tests/deploy/node/
    #     - unzip -P ${UNZIP_CODE} travis_node.zip
    #     - cd ${WORKSPACE}/PlatON-Tests/
    #     - pip install --user -r requirements.txt
    #     - cp -f ${WORKSPACE}/build/bin/platon ${WORKSPACE}/PlatON-Tests/deploy/rely/bin/
    #     - python run.py --node ./deploy/node/travis_node.yml --type ppos
